Exception caught @19:44:51 09.26.12
    Message: An error occured while fetching record data
    SQL: Select * from 546ArchChat where
    File: /home/course/546/public_html/121/archStart/BizDataLayer/chatData.php
    Line: 17
    Trace: #0 /home/course/546/public_html/121/archStart/svcLayer/chat/chatUtil.php(8): getChatData()
#1 [internal function]: getChat(NULL, '129.21.66.228', NULL)
#2 /home/course/546/public_html/121/archStart/mid.php(12): call_user_func('getChat', NULL, '129.21.66.228', NULL)
#3 {main}
Exception caught @21:42:19 09.26.12
    Message: An error occured while fetching record data
    SQL: Select * from 546ArchChat where
    File: /home/course/546/public_html/121/archStart/BizDataLayer/chatData.php
    Line: 17
    Trace: #0 /home/course/546/public_html/121/archStart/svcLayer/chat/chatUtil.php(8): getChatData()
#1 [internal function]: getChat(NULL, '69.207.187.195', NULL)
#2 /home/course/546/public_html/121/archStart/mid.php(12): call_user_func('getChat', NULL, '69.207.187.195', NULL)
#3 {main}
Exception caught @21:49:48 09.26.12
    Message: An error occured while fetching record data
    SQL: Select * from 546ArchChat where
    File: /home/course/546/public_html/121/archStart/BizDataLayer/chatData.php
    Line: 17
    Trace: #0 /home/course/546/public_html/121/archStart/svcLayer/chat/chatUtil.php(8): getChatData()
#1 [internal function]: getChat(NULL, '69.207.187.195', NULL)
#2 /home/course/546/public_html/121/archStart/mid.php(12): call_user_func('getChat', NULL, '69.207.187.195', NULL)
#3 {main}
Exception caught @21:49:55 09.26.12
    Message: An error occured while fetching record data
    SQL: Select * from 546ArchChat where
    File: /home/course/546/public_html/121/archStart/BizDataLayer/chatData.php
    Line: 17
    Trace: #0 /home/course/546/public_html/121/archStart/svcLayer/chat/chatUtil.php(8): getChatData()
#1 [internal function]: getChat(NULL, '69.207.187.195', NULL)
#2 /home/course/546/public_html/121/archStart/mid.php(12): call_user_func('getChat', NULL, '69.207.187.195', NULL)
#3 {main}
Exception caught @19:10:17 10.14.12
    Message: An error occured while fetching record data
    SQL: Select * from 546ArchChat
    File: /Users/jdesulme/Documents/Workspace/Connect4/BizDataLayer/chatData.php
    Line: 21
    Trace: #0 /Users/jdesulme/Documents/Workspace/Connect4/svcLayer/chat/chatUtil.php(10): getChatData()
#1 [internal function]: getChat(NULL, '::1', NULL)
#2 /Users/jdesulme/Documents/Workspace/Connect4/mid.php(14): call_user_func('getChat', NULL, '::1', NULL)
#3 {main}
Exception caught @19:11:15 10.14.12
    Message: An error occured while fetching record data
    SQL: Select * from 546ArchChat
    File: /Users/jdesulme/Documents/Workspace/Connect4/BizDataLayer/chatData.php
    Line: 21
    Trace: #0 /Users/jdesulme/Documents/Workspace/Connect4/svcLayer/chat/chatUtil.php(10): getChatData()
#1 [internal function]: getChat(NULL, '::1', NULL)
#2 /Users/jdesulme/Documents/Workspace/Connect4/mid.php(14): call_user_func('getChat', NULL, '::1', NULL)
#3 {main}
